version: '3'

services:
  backend:
    build:
      context: ./birth-map-api
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
    environment:
      - NODE_ENV=development
      - PORT=6001
    volumes:
      - ./birth-map-api:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./test_env
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./test_env:/usr/src/app
      - /usr/src/app/node_modules
