version: '3'

services:
  backend:
    build:
      context: ./birth-map-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./birth-map-api:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./test_env
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./test_env:/usr/src/app
      - /usr/src/app/node_modules
